// The kernel the Level Zero spike launches. It is written by hand rather than
// generated by Vx on purpose: its job is to be a known-good image, so that a
// failure in the spike is a failure of the spike and not of Vx's device
// lowering, which is a separate open problem.
//
// The parameter list is Vx's flattened rank-2 tensor ABI: two pointers (the
// memref's allocated and aligned base), an offset, two sizes and two strides,
// each its own kernel argument. Nothing here is an aggregate.
//
// One work-item per element, so the kernel has no loop; the index is computed
// from the strides the way the device twin will have to compute it.

__kernel void add_one(__global float *allocated, __global float *aligned,
                      unsigned long offset, unsigned long n0, unsigned long n1,
                      unsigned long s0, unsigned long s1) {
  unsigned long gid = get_global_id(0);
  // A work-group is launched whole, so the last one usually has work-items past
  // the tensor's end. They must do nothing.
  if (gid >= n0 * n1)
    return;
  unsigned long row = gid / n1;
  unsigned long col = gid % n1;
  unsigned long idx = offset + row * s0 + col * s1;
  aligned[idx] = aligned[idx] + 1.0f;
}
